[common]
origin = "http://golang.fzf404.top" # 域名
port = 8080 # 服务端口 
article_page = 12 # 文章每页条数

[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "1234567"
database = "qinli"
config = "charset=utf8&parseTime=true"

[redis]
addr = "127.0.0.1:6379"

[jwt]
key = "zff404-todolist-secret" # 签名密钥
issuer = "Zouly" # 发行人
expires = 604800 # token过期时间 (7 day)
